# Numpy for Data Scientists
---

In [3]:
import numpy as np

## 1. Numpy array attributes

In [4]:
def print_info(x):
    print(x)
    print(f"Type = {type(x)}")
    print(f"[ndim] The number of dimensions(axes) of the array = {x.ndim}")
    print(f"[shape] The size of the array in each dimension(axe) = {x.shape}")
    print(f"[size] The total number of elements of the array = {x.size}")
    print(f"[dtype] The type of the elements in the array = {x.dtype}")
    print(f"[itemsize] the size in bytes of each element of the array = {x.itemsize}")

## 2. Numpy array creation
### 2.1 Numpy array can be created from list or tuple as a argument. Not from numeric arguments. 

In [5]:
a = np.array(1, 2, 3, 4)  # Error!

ValueError: only 2 non-keyword arguments accepted

In [6]:
a = np.array([1, 2, 3, 4]) # Correct! from list
print_info(a)


[1 2 3 4]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 1
[shape] The size of the array in each dimension(axe) = (4,)
[size] The total number of elements of the array = 4
[dtype] The type of the elements in the array = int32
[itemsize] the size in bytes of each element of the array = 4


In [7]:
b = np.array((1, 2, 3, 4)) # Correct! from tuple
print_info(b)

[1 2 3 4]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 1
[shape] The size of the array in each dimension(axe) = (4,)
[size] The total number of elements of the array = 4
[dtype] The type of the elements in the array = int32
[itemsize] the size in bytes of each element of the array = 4


In [8]:
c = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print_info(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 2
[shape] The size of the array in each dimension(axe) = (3, 3)
[size] The total number of elements of the array = 9
[dtype] The type of the elements in the array = int32
[itemsize] the size in bytes of each element of the array = 4


### 2.2 Util functions can create an array full of zeros or ones with shape argument.

In [9]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 2.3 Sequence array can be created from range arguments with a step.
 - Default is increased 1 step from zero.
 - The end of the range is not included.


In [16]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
b = np.arange(0, 10, 1)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
c = np.arange(2, 10, 2)
print(c)

[2 4 6 8]


### 2.4 Sequence array can be created by slicing.
 - The end of the range is included.

In [12]:
b = np.linspace(0, 10, 5)
print_info(b)

[ 0.   2.5  5.   7.5 10. ]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 1
[shape] The size of the array in each dimension(axe) = (5,)
[size] The total number of elements of the array = 5
[dtype] The type of the elements in the array = float64
[itemsize] the size in bytes of each element of the array = 8


## 3. Reshape
### Display with layout with below order:
 - the last axis is printed from left to right,
 - the second-to-last is printed from top to bottom,
 - the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

In [25]:
a = np.arange(10)
print(f"a = {a}")

reshape_a = a.reshape((5, 2))
print(f"After reshaping, the previous a = {a}")
print(f"The reshaped a = \n{reshape_a}")

a = [0 1 2 3 4 5 6 7 8 9]
After reshaping, the previous a = [0 1 2 3 4 5 6 7 8 9]
The reshaped a = 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [26]:
b = np.arange(12)
b.reshape((3, 2, 2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [27]:
c = np.arange(10000)
c.reshape((100, 100))


array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

## 4. Operations

In [31]:
A = np.array([[1, 1],
              [1, 1]])
B = np.array([[2, 3],
              [4, 5]])
print("elementwise product")
print(A*B)

print("matrix product")
print(A@B)


elementwise product
[[2 3]
 [4 5]]
matrix product
[[6 8]
 [6 8]]
