# Numpy sample codes for Data Scientists
---

In [1]:
import numpy as np

## 1. Numpy array attributes

In [2]:
def print_info(x):
    print(x)
    print(f"Type = {type(x)}")
    print(f"[ndim] The number of dimensions(axes) of the array = {x.ndim}")
    print(f"[shape] The size of the array in each dimension(axe) = {x.shape}")
    print(f"[size] The total number of elements of the array = {x.size}")
    print(f"[dtype] The type of the elements in the array = {x.dtype}")
    print(f"[itemsize] the size in bytes of each element of the array = {x.itemsize}")

## 2. Numpy array creation
### 2.1 Numpy array can be created from list or tuple as a argument. Not from numeric arguments. 
- np.array(1, 2, 3, 4)  # Error!

In [3]:
a = np.array([1, 2, 3, 4]) # Correct! from list
print_info(a)


[1 2 3 4]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 1
[shape] The size of the array in each dimension(axe) = (4,)
[size] The total number of elements of the array = 4
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


In [4]:
b = np.array((1, 2, 3, 4)) # Correct! from tuple
print_info(b)

[1 2 3 4]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 1
[shape] The size of the array in each dimension(axe) = (4,)
[size] The total number of elements of the array = 4
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


In [5]:
c = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print_info(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 2
[shape] The size of the array in each dimension(axe) = (3, 3)
[size] The total number of elements of the array = 9
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


### 2.2 Util functions can create an array full of zeros or ones with shape argument.

In [6]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 2.3 Sequence array can be created from range arguments with a step.
 - Default is increased 1 step from zero.
 - The end of the range is not included.


In [8]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
b = np.arange(0, 10, 1)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
c = np.arange(2, 10, 2)
print(c)

[2 4 6 8]


### 2.4 Sequence array can be created by slicing.
 - The end of the range is included.

In [11]:
b = np.linspace(0, 10, 5)
print_info(b)

[ 0.   2.5  5.   7.5 10. ]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 1
[shape] The size of the array in each dimension(axe) = (5,)
[size] The total number of elements of the array = 5
[dtype] The type of the elements in the array = float64
[itemsize] the size in bytes of each element of the array = 8


## 3. Reshape
### Display with layout with below order:
 - the last axis is printed from left to right,
 - the second-to-last is printed from top to bottom,
 - the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

In [12]:
a = np.arange(10)
print(f"a = {a}")

reshape_a = a.reshape((5, 2))
print(f"After reshaping, the previous a = {a}")
print(f"The reshaped a = \n{reshape_a}")

a = [0 1 2 3 4 5 6 7 8 9]
After reshaping, the previous a = [0 1 2 3 4 5 6 7 8 9]
The reshaped a = 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
b = np.arange(12)
b.reshape((3, 2, 2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [14]:
c = np.arange(10000)
c.reshape((100, 100))


array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

## 4. Operations

In [15]:
A = np.array([[1, 1],
              [1, 1]])

B = np.array([[2, 3],
              [4, 5]])

print("elementwise product")
print(A*B)

elementwise product
[[2 3]
 [4 5]]


In [16]:
print("matrix product")
print(A@B)

matrix product
[[6 8]
 [6 8]]


In [17]:
print("matrix product")
print(A.dot(B))


matrix product
[[6 8]
 [6 8]]


## 4. Indexing
### 4.1 Slicing in one dimension
 - Basic slicing : [start : stop : step]
 - Negative indices means counting from the end of the array.
 - All arrays generated by basic slicing are always views of the original array.
 - Default step is one.
 - Blank means min/max of the start and end.
 

In [18]:
a = np.arange(10)
print(f'original array = {a}')

b = a[1:7:2]
print(f'sliced array = {b}')
print(f'original array = {a}')

original array = [0 1 2 3 4 5 6 7 8 9]
sliced array = [1 3 5]
original array = [0 1 2 3 4 5 6 7 8 9]


In [19]:
# Start = End(10)-5
a[-5:10]

array([5, 6, 7, 8, 9])

In [20]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
a[::-2]

array([9, 7, 5, 3, 1])

In [22]:
a[5::-1]

array([5, 4, 3, 2, 1, 0])

### 4.2 Slicing in multi dimensions
 - We can slice only in the first dimension(axe). No matter how the shape is complex, the effective dimension is the first like (2, .., .., .., .....) 
 - Ex) [ [1, 2, 3],
         [4, 5, 6],
         [7, 8, 9] ]
 - Possible slicing example: [[1, 2, 3]] or [[1, 2, 3], [4, 5, 6]]
 - Impossible : [[1, 2], [4, 5]]


In [32]:
a = np.array([[[1,1], [2,2], [3,3]],
              [[4,4], [5,5], [6,6]]])
print_info(a)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 3
[shape] The size of the array in each dimension(axe) = (2, 3, 2)
[size] The total number of elements of the array = 12
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


In [38]:
a[:1]

array([[[1, 1],
        [2, 2],
        [3, 3]]])

In [48]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

c = b[:2]
print_info(c)

[[1 2 3]
 [4 5 6]]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 2
[shape] The size of the array in each dimension(axe) = (2, 3)
[size] The total number of elements of the array = 6
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


In [53]:
b = np.array([[[1], [2], [3]],
              [[4], [5], [6]],
              [[7], [8], [9]],
              [[10], [11], [12]]])

print_info(b)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 3
[shape] The size of the array in each dimension(axe) = (4, 3, 1)
[size] The total number of elements of the array = 12
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


In [55]:
b[:2]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

### Ellipsis expands to the number of : objects needed for the selection tuple to index all dimensions.

In [56]:
c = b[..., 0]
print_info(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 2
[shape] The size of the array in each dimension(axe) = (4, 3)
[size] The total number of elements of the array = 12
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


In [57]:
d = np.array([[[[1], [2], [3]],
              [[4], [5], [6]]],
              [[[7], [8], [9]],
              [[10], [11], [12]]]])
print_info(d)

[[[[ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]]]


 [[[ 7]
   [ 8]
   [ 9]]

  [[10]
   [11]
   [12]]]]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 4
[shape] The size of the array in each dimension(axe) = (2, 2, 3, 1)
[size] The total number of elements of the array = 12
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


In [59]:
e = d[..., 0]
print_info(e)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 3
[shape] The size of the array in each dimension(axe) = (2, 2, 3)
[size] The total number of elements of the array = 12
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8
