# Everything about Numpy for Data Scientists

In [1]:
import numpy as np



## 1. Numpy array information

In [23]:
def print_array_info(x):
    print(x)
    print(f"Type = {type(x)}")
    print(f"[ndim] The number of dimensions(axes) of the array = {x.ndim}")
    print(f"[shape] The size of the array in each dimension(axe) = {x.shape}")
    print(f"[size] The total number of elements of the array = {x.size}")
    print(f"[dtype] The type of the elements in the array = {x.dtype}")
    print(f"[itemsize] the size in bytes of each element of the array = {x.itemsize}")

## 2. Numpy array creation
### 2.1 Numpy array can be created from list or tuple as a argument. Not numeric arguments. 

In [24]:
a = np.array(1, 2, 3, 4)  # Error!

ValueError: only 2 non-keyword arguments accepted

In [25]:
a = np.array([1, 2, 3, 4]) # Correct! from list
print_array_info(a)


[1 2 3 4]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 1
[shape] The size of the array in each dimension(axe) = (4,)
[size] The total number of elements of the array = 4
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


In [26]:
b = np.array((1, 2, 3, 4)) # Correct! from tuple
print_array_info(b)

[1 2 3 4]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 1
[shape] The size of the array in each dimension(axe) = (4,)
[size] The total number of elements of the array = 4
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


In [27]:
c = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print_array_info(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 2
[shape] The size of the array in each dimension(axe) = (3, 3)
[size] The total number of elements of the array = 9
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


### 2.2 Util functions can create an array full of zeros or ones with shape argument.

In [28]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 2.3 Sequence array can be created from range arguments with a step.
##### The end of the range is not included.

In [45]:
a = np.arange(0, 10, 2)
print_array_info(a)

[0 2 4 6 8]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 1
[shape] The size of the array in each dimension(axe) = (5,)
[size] The total number of elements of the array = 5
[dtype] The type of the elements in the array = int64
[itemsize] the size in bytes of each element of the array = 8


### 2.3 Sequence array can be created by slicing.
##### The end of the range is included.

In [46]:
b = np.linspace(0, 10, 5)
print_array_info(b)




[ 0.   2.5  5.   7.5 10. ]
Type = <class 'numpy.ndarray'>
[ndim] The number of dimensions(axes) of the array = 1
[shape] The size of the array in each dimension(axe) = (5,)
[size] The total number of elements of the array = 5
[dtype] The type of the elements in the array = float64
[itemsize] the size in bytes of each element of the array = 8
